// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var NeocitiesHaxeTest = function() { };
NeocitiesHaxeTest.main = function() {
	NeocitiesHaxeTest.print_twice("This is a Haxe script that I'm testing, don't mind it, it doesn't do anything other than print this message, and a duplicate of it with some random YonKaGor song's lyrics at the end.");
};
NeocitiesHaxeTest.print_twice = function(s) {
	var phrases = ["('Cause whenever I choose to remain to linger in the rain...)","(If i told one, someone, everyone, a rumor just for fun!)","(And so I gave myself to you... I didn't know I was used...)","(And now I'll wave 'So Long'! The train will shortly move along!)"];
	var message = s;
	console.log("NeocitiesHaxeTest.hx:24:",message);
	var message = s;
	var randomIndex = Std.random(phrases.length);
	var pickedPhrase = phrases[randomIndex];
	message = s + " " + pickedPhrase;
	console.log("NeocitiesHaxeTest.hx:24:",message);
};
var Std = function() { };
Std.random = function(x) {
	if(x <= 0) {
		return 0;
	} else {
		return Math.floor(Math.random() * x);
	}
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
NeocitiesHaxeTest.main();
})({});
